"""fix_ip_address_field_length

Revision ID: f35a1b8df3f9
Revises: db8cc1b545ff
Create Date: 2025-07-26 22:41:27.168546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35a1b8df3f9'
down_revision: Union[str, None] = 'db8cc1b545ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)
    # ### end Alembic commands ### 