"""Initial database schema

Revision ID: db8cc1b545ff
Revises: 
Create Date: 2025-07-26 22:08:21.156931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db8cc1b545ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_items'))
    )
    op.create_index('ix_content_domain_status', 'content_items', ['source_domain', 'status'], unique=False)
    op.create_index(op.f('ix_content_items_id'), 'content_items', ['id'], unique=False)
    op.create_index(op.f('ix_content_items_source_domain'), 'content_items', ['source_domain'], unique=False)
    op.create_index(op.f('ix_content_items_status'), 'content_items', ['status'], unique=False)
    op.create_index(op.f('ix_content_items_url'), 'content_items', ['url'], unique=True)
    op.create_index('ix_content_scraped_status', 'content_items', ['scraped_at', 'status'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_ip_address'), 'user_sessions', ['ip_address'], unique=False)
    op.create_index('ix_user_sessions_ip_created', 'user_sessions', ['ip_address', 'created_at'], unique=False)
    op.create_index('ix_user_sessions_last_activity', 'user_sessions', ['last_activity'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_table('ai_analysis_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('analysis_type', sa.String(length=100), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], name=op.f('fk_ai_analysis_results_content_id_content_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analysis_results'))
    )
    op.create_index('ix_ai_analysis_content_type', 'ai_analysis_results', ['content_id', 'analysis_type'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_analysis_type'), 'ai_analysis_results', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_content_id'), 'ai_analysis_results', ['content_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_created_at'), 'ai_analysis_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_analysis_results_id'), 'ai_analysis_results', ['id'], unique=False)
    op.create_index('ix_ai_analysis_type_confidence', 'ai_analysis_results', ['analysis_type', 'confidence'], unique=False)
    op.create_table('ai_workflow_executions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowstatus'), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], name=op.f('fk_ai_workflow_executions_content_id_content_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_workflow_executions'))
    )
    op.create_index(op.f('ix_ai_workflow_executions_content_id'), 'ai_workflow_executions', ['content_id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_executions_created_at'), 'ai_workflow_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_workflow_executions_id'), 'ai_workflow_executions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_workflow_executions_status'), 'ai_workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_workflow_executions_workflow_type'), 'ai_workflow_executions', ['workflow_type'], unique=False)
    op.create_index('ix_workflow_created_status', 'ai_workflow_executions', ['created_at', 'status'], unique=False)
    op.create_index('ix_workflow_execution_time', 'ai_workflow_executions', ['execution_time'], unique=False)
    op.create_index('ix_workflow_type_status', 'ai_workflow_executions', ['workflow_type', 'status'], unique=False)
    op.create_table('content_metadata',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('metadata_type', sa.String(length=100), nullable=False),
    sa.Column('metadata_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], name=op.f('fk_content_metadata_content_id_content_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_metadata')),
    sa.UniqueConstraint('content_id', 'metadata_type', name='uq_content_metadata_type')
    )
    op.create_index(op.f('ix_content_metadata_content_id'), 'content_metadata', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_metadata_id'), 'content_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_content_metadata_metadata_type'), 'content_metadata', ['metadata_type'], unique=False)
    op.create_index('ix_content_metadata_type', 'content_metadata', ['content_id', 'metadata_type'], unique=False)
    op.create_table('fact_check_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.Enum('TRUE', 'MOSTLY_TRUE', 'MIXED', 'MOSTLY_FALSE', 'FALSE', 'UNVERIFIABLE', 'OPINION', name='factcheckverdict'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], name=op.f('fk_fact_check_results_content_id_content_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], name=op.f('fk_fact_check_results_session_id_user_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_check_results'))
    )
    op.create_index('ix_fact_check_created', 'fact_check_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_fact_check_results_content_id'), 'fact_check_results', ['content_id'], unique=False)
    op.create_index(op.f('ix_fact_check_results_id'), 'fact_check_results', ['id'], unique=False)
    op.create_index(op.f('ix_fact_check_results_session_id'), 'fact_check_results', ['session_id'], unique=False)
    op.create_index(op.f('ix_fact_check_results_verdict'), 'fact_check_results', ['verdict'], unique=False)
    op.create_index('ix_fact_check_verdict_confidence', 'fact_check_results', ['verdict', 'confidence_score'], unique=False)
    op.create_table('feed_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Enum('TRUE', 'MOSTLY_TRUE', 'MIXED', 'MOSTLY_FALSE', 'FALSE', 'UNVERIFIABLE', 'OPINION', name='factcheckverdict'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], name=op.f('fk_feed_posts_content_id_content_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], name=op.f('fk_feed_posts_session_id_user_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_posts'))
    )
    op.create_index('ix_feed_post_confidence', 'feed_posts', ['confidence'], unique=False)
    op.create_index('ix_feed_post_verdict_created', 'feed_posts', ['verdict', 'created_at'], unique=False)
    op.create_index(op.f('ix_feed_posts_content_id'), 'feed_posts', ['content_id'], unique=False)
    op.create_index(op.f('ix_feed_posts_created_at'), 'feed_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_feed_posts_id'), 'feed_posts', ['id'], unique=False)
    op.create_index(op.f('ix_feed_posts_session_id'), 'feed_posts', ['session_id'], unique=False)
    op.create_index(op.f('ix_feed_posts_verdict'), 'feed_posts', ['verdict'], unique=False)
    op.create_table('rate_limit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], name=op.f('fk_rate_limit_logs_session_id_user_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limit_logs'))
    )
    op.create_index('ix_rate_limit_endpoint_window', 'rate_limit_logs', ['endpoint', 'window_start'], unique=False)
    op.create_index(op.f('ix_rate_limit_logs_endpoint'), 'rate_limit_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_rate_limit_logs_id'), 'rate_limit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limit_logs_session_id'), 'rate_limit_logs', ['session_id'], unique=False)
    op.create_index('ix_rate_limit_session_endpoint', 'rate_limit_logs', ['session_id', 'endpoint'], unique=False)
    op.create_index('ix_rate_limit_window', 'rate_limit_logs', ['window_start', 'window_end'], unique=False)
    op.create_table('fact_check_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fact_check_id', sa.BigInteger(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('NEWS_ARTICLE', 'ACADEMIC_PAPER', 'GOVERNMENT', 'FACT_CHECKER', 'EXPERT_OPINION', 'SOCIAL_MEDIA', 'BLOG', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fact_check_id'], ['fact_check_results.id'], name=op.f('fk_fact_check_sources_fact_check_id_fact_check_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_check_sources'))
    )
    op.create_index('ix_fact_check_source_relevance', 'fact_check_sources', ['relevance_score'], unique=False)
    op.create_index('ix_fact_check_source_type', 'fact_check_sources', ['fact_check_id', 'source_type'], unique=False)
    op.create_index(op.f('ix_fact_check_sources_fact_check_id'), 'fact_check_sources', ['fact_check_id'], unique=False)
    op.create_index(op.f('ix_fact_check_sources_id'), 'fact_check_sources', ['id'], unique=False)
    op.create_index(op.f('ix_fact_check_sources_source_type'), 'fact_check_sources', ['source_type'], unique=False)
    op.create_table('feed_likes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['feed_posts.id'], name=op.f('fk_feed_likes_post_id_feed_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], name=op.f('fk_feed_likes_session_id_user_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_likes')),
    sa.UniqueConstraint('post_id', 'session_id', name='uq_feed_like_post_session')
    )
    op.create_index('ix_feed_like_created', 'feed_likes', ['created_at'], unique=False)
    op.create_index(op.f('ix_feed_likes_id'), 'feed_likes', ['id'], unique=False)
    op.create_index(op.f('ix_feed_likes_post_id'), 'feed_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_feed_likes_session_id'), 'feed_likes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_likes_session_id'), table_name='feed_likes')
    op.drop_index(op.f('ix_feed_likes_post_id'), table_name='feed_likes')
    op.drop_index(op.f('ix_feed_likes_id'), table_name='feed_likes')
    op.drop_index('ix_feed_like_created', table_name='feed_likes')
    op.drop_table('feed_likes')
    op.drop_index(op.f('ix_fact_check_sources_source_type'), table_name='fact_check_sources')
    op.drop_index(op.f('ix_fact_check_sources_id'), table_name='fact_check_sources')
    op.drop_index(op.f('ix_fact_check_sources_fact_check_id'), table_name='fact_check_sources')
    op.drop_index('ix_fact_check_source_type', table_name='fact_check_sources')
    op.drop_index('ix_fact_check_source_relevance', table_name='fact_check_sources')
    op.drop_table('fact_check_sources')
    op.drop_index('ix_rate_limit_window', table_name='rate_limit_logs')
    op.drop_index('ix_rate_limit_session_endpoint', table_name='rate_limit_logs')
    op.drop_index(op.f('ix_rate_limit_logs_session_id'), table_name='rate_limit_logs')
    op.drop_index(op.f('ix_rate_limit_logs_id'), table_name='rate_limit_logs')
    op.drop_index(op.f('ix_rate_limit_logs_endpoint'), table_name='rate_limit_logs')
    op.drop_index('ix_rate_limit_endpoint_window', table_name='rate_limit_logs')
    op.drop_table('rate_limit_logs')
    op.drop_index(op.f('ix_feed_posts_verdict'), table_name='feed_posts')
    op.drop_index(op.f('ix_feed_posts_session_id'), table_name='feed_posts')
    op.drop_index(op.f('ix_feed_posts_id'), table_name='feed_posts')
    op.drop_index(op.f('ix_feed_posts_created_at'), table_name='feed_posts')
    op.drop_index(op.f('ix_feed_posts_content_id'), table_name='feed_posts')
    op.drop_index('ix_feed_post_verdict_created', table_name='feed_posts')
    op.drop_index('ix_feed_post_confidence', table_name='feed_posts')
    op.drop_table('feed_posts')
    op.drop_index('ix_fact_check_verdict_confidence', table_name='fact_check_results')
    op.drop_index(op.f('ix_fact_check_results_verdict'), table_name='fact_check_results')
    op.drop_index(op.f('ix_fact_check_results_session_id'), table_name='fact_check_results')
    op.drop_index(op.f('ix_fact_check_results_id'), table_name='fact_check_results')
    op.drop_index(op.f('ix_fact_check_results_content_id'), table_name='fact_check_results')
    op.drop_index('ix_fact_check_created', table_name='fact_check_results')
    op.drop_table('fact_check_results')
    op.drop_index('ix_content_metadata_type', table_name='content_metadata')
    op.drop_index(op.f('ix_content_metadata_metadata_type'), table_name='content_metadata')
    op.drop_index(op.f('ix_content_metadata_id'), table_name='content_metadata')
    op.drop_index(op.f('ix_content_metadata_content_id'), table_name='content_metadata')
    op.drop_table('content_metadata')
    op.drop_index('ix_workflow_type_status', table_name='ai_workflow_executions')
    op.drop_index('ix_workflow_execution_time', table_name='ai_workflow_executions')
    op.drop_index('ix_workflow_created_status', table_name='ai_workflow_executions')
    op.drop_index(op.f('ix_ai_workflow_executions_workflow_type'), table_name='ai_workflow_executions')
    op.drop_index(op.f('ix_ai_workflow_executions_status'), table_name='ai_workflow_executions')
    op.drop_index(op.f('ix_ai_workflow_executions_id'), table_name='ai_workflow_executions')
    op.drop_index(op.f('ix_ai_workflow_executions_created_at'), table_name='ai_workflow_executions')
    op.drop_index(op.f('ix_ai_workflow_executions_content_id'), table_name='ai_workflow_executions')
    op.drop_table('ai_workflow_executions')
    op.drop_index('ix_ai_analysis_type_confidence', table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_id'), table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_created_at'), table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_content_id'), table_name='ai_analysis_results')
    op.drop_index(op.f('ix_ai_analysis_results_analysis_type'), table_name='ai_analysis_results')
    op.drop_index('ix_ai_analysis_content_type', table_name='ai_analysis_results')
    op.drop_table('ai_analysis_results')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_index('ix_user_sessions_last_activity', table_name='user_sessions')
    op.drop_index('ix_user_sessions_ip_created', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_ip_address'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_content_scraped_status', table_name='content_items')
    op.drop_index(op.f('ix_content_items_url'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_status'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_source_domain'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_id'), table_name='content_items')
    op.drop_index('ix_content_domain_status', table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ### 